### ISSUE TITLE
Una consulta!!

### ISSUE THREAD

**Issue by edwarbad23** [team-racoon/nsh-atmosphere#7]
Buenos dias antes que todo muchas gracias por este paquete siempre lo descargo por que lo tienen todo en orden!!!

Mi consulta es la siguiente:
Hay una forma de como desactivar el Incognito y el 90dns de la particion "sysnand (CFW)" o mejor dicho de la pirateria? Les explico, yo antes bajaba el atmosphere oficial, y la utilizaba  el hack en la sysnand y me conectaba a internet (obvio con todos los juegos originales en mi consola, nada pirateado) y hasta ahora no he tenido problemas de baneo de consola, por cuestiones de estudio me fui a un pais que el internet es muy limitado y bueno ahi fue cuando comence a utlizar su repo que bloqueba las conexiones de internet y lo utilizaba en la emunand, ahora he regresado a mi pais para unas vacaciones y quiero otra vez utilizar mi internet en la sysnand con CFW y jugar en linea o utllizar cheats, pero su repo me lo prohibe aunque este en la sysnand con cfw, asi que queria saber si hay una forma de ya no ponerlo 
gracias
P.D: tienen link de instagram?

**Comment by Borrajo** [comment]
Buenas tardes, creo haberte entendido, usas el CFW sobre la sysnand pero no tienen juegos piratas alli, y solo quieres usar atmosphere para meter cheats y modificaciones a los juegos originales que tienes. cierto ? 
Eso no sería lo más seguro de hacer, puede correr algun riesgo de baneo. Pero si de todas formas quisieras desactivar el incognito ( bajo tu responsabilidad ) debes editar los archivos exosphere.ini en la raiz y el archivo hekate_ipl en la carpeta bootloader.
https://github.com/team-racoon/nsh-atmosphere/blob/3aff6084594accf882a33be3fa5f075aaa1cb411/exosphere.ini#L54
https://github.com/team-racoon/nsh-atmosphere/blob/3aff6084594accf882a33be3fa5f075aaa1cb411/bootloader/hekate_ipl.ini#L21

Si tienes alguna duda puedes pasar por nuestro grupo: https://t.me/nsh_atmosphere

Saludos
